from django.urls import path 
from home import views


urlpatterns = [
    # path('<int:year>/<str:month>/', views.home, name = 'home' )
    path('', views.campus, name = 'campus' ),
    path('home', views.home, name = 'home' ),
    path('events', views.all_events, name = 'list_events' ),
    path('add_venue', views.add_venue, name = 'add-venue' ),
    path('add_event', views.add_event, name = 'add-event' ),
    path('profile_list', views.profile_list, name = 'profile_list' ),
    path('profile/<int:pk>', views.profile, name = 'profile' ),
    path('meep_like/<int:pk>', views.meep_like, name = 'meep_like' ),
    path('rehb', views.rehb, name = 'rehb' ),
    path('applied', views.applied, name = 'applied' ),
    path('comp', views.comp, name = 'comp' ),
    path('engin', views.engin, name = 'engin' ),
    path('islamic_study', views.islamic_study, name = 'islamic_study' ),
    path('phsyco', views.phsyco, name = 'phsyco' ),
    path('chemis', views.chemis, name = 'chemis' ),
    path('socio', views.socio, name = 'socio' ),
    path('complaint', views.complaint, name = 'complaint' ),       
    path('biotech', views.biotech, name = 'biotech' ),       
    path('hnd', views.hnd, name = 'hnd' ),       
    path('mlt', views.mlt, name = 'mlt' ),       
    path('dpt', views.dpt, name = 'dpt' ),       
    path('slp', views.slp, name = 'slp' ),       
    path('mit', views.mit, name = 'mit' ),       
    path('food_science', views.food_science, name = 'food_science' ),       
    path('botany', views.botany, name = 'botany' ),       
    path('softeng', views.softeng, name = 'softeng' ),       
    path('infotech', views.infotech, name = 'infotech' ),       
    path('datascience', views.datascience, name = 'datascience' ),       
    path('cybersec', views.cybersec, name = 'cybersec' ),       
    path('computersci', views.computersci, name = 'computersci' ),       
    path('electricalengin', views.electricalengin, name = 'electricalengin' ),       
    path('bioinformatics', views.bioinformatics, name = 'bioinformatics' ),       
    path('phsycodiploma', views.phsycodiploma, name = 'phsycodiploma' ),       
    path('appliedphsyco', views.appliedphsyco, name = 'appliedphsyco' ),       
    path('chemistry', views.chemistry, name = 'chemistry' ),       
    path('biochem', views.biochem, name = 'biochem' ),       
    path('criminology', views.criminology, name = 'criminology' ),       
    path('masscomm', views.masscomm, name = 'masscomm' ),       
    path('mediasci', views.mediasci, name = 'mediasci' ),       
    path('sociology', views.sociology, name = 'sociology' ),       
] 
