# Generated by Django 4.2 on 2023-04-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='wemail_address',
            new_name='email_address',
        ),
    ]
