# Generated by Django 4.1.7 on 2023-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_wemail_address_venue_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
