# Generated by Django 4.1.7 on 2023-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue_image',
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
