# Generated by Django 5.0.3 on 2024-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_category_meep_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='title',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
