# Generated by Django 5.0.3 on 2024-03-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile_facebook_link_profile_homepgae_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepgae_link',
            new_name='homepage_link',
        ),
    ]
