# Generated by Django 5.0.3 on 2024-03-26 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_video_created_at_video_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default='sunny', on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
