# Generated by Django 5.0.3 on 2024-03-26 08:39

import django.db.models.deletion
import home.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_delete_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('video', models.FileField(upload_to='video/%y', validators=[home.validators.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=17, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
