# Generated by Django 5.0.3 on 2024-03-27 05:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_meep_body_alter_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meep',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
